import React, { useContext, useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { Context } from "../context";

const Layout = ({ children }) => {
  const router = useRouter();
  const { state, dispatch } = useContext(Context);
  const [initialLoading, setInitialLoading] = useState(false);
  const [finalloading, setfinalLoading] = useState(false);

  const logOut = () => {
    const response = confirm("Are you sure to sign out ?");
    if (response) {
      dispatch({
        type: "LOGOUT",
        payload: {},
      });
      router.push("/");
    }
  };

  useEffect(() => {
    setTimeout(() => {
      setInitialLoading(true);
    }, 200);
    setTimeout(() => {
      setfinalLoading(true);
    }, 1000);
  }, []);


  return (
    <>
      <div
        className={`w-full h-screen transition-all duration-1000 absolute bg-white   ${
          !initialLoading ? "opacity-100 " : "opacity-0"
        } `}
      ></div>
      <div
        className={`w-full  h-screen transition-all duration-1000 ${
          finalloading && "absolute"
        }`}
      >
        <Head>
          <title>Monlech</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="w-full h-20 bg-slate-200 flex justify-between items-center pl-10 shadow-lg ">
          <h2 className="font-bold  text-2xl md:text-5xl">Monlech</h2>
          <div className="flex w-56 items-center justify-around ">
            {!state.loggedIn ? (
              <>
                <button
                  onClick={() => router.push("/")}
                  className="bg-sky-600 text-white font-bold px-5 py-2 rounded-xl transition-all duration-500 hover:scale-105"
                >
                  Sign in
                </button>
                <button
                  onClick={() => router.push("/SignUp")}
                  className="bg-emerald-500 text-white font-bold px-5 py-2 rounded-xl transition-all duration-500 hover:scale-105"
                >
                  Sign up
                </button>
              </>
            ) : (
              <>
                <h2 className="font-bold text-2xl">{state.data.username}</h2>
                <button
                  onClick={logOut}
                  className="bg-red-500 text-white font-bold px-5 py-2 rounded-xl transition-all duration-500 hover:scale-105"
                >
                  Sign out
                </button>
              </>
            )}
          </div>
        </div>
        <main className="w-full">{children}</main>
      </div>
    </>
  );
};

export default Layout;
